#!/bin/bash

#I have various drives on a windows PC that I like to mount as the local user.
#Create directories if not already there.
#All machines have a static IP.

if [ -d "$HOME/windowsMounts/jwinalienC" ]; then
    sudo mount //192.168.1.102/C $HOME/windowsMounts/jwinalienC -o user=jwinalien -o uid=1000 -o gid=1000
elif [ -d "$HOME/windowsMounts/" ]; then	
    mkdir "$HOME/windowsMounts/jwinalienC"
    sudo mount //192.168.1.102/C $HOME/windowsMounts/jwinalienC -o user=jwinalien -o uid=1000 -o gid=1000
else
    mkdir "$HOME/windowsMounts/"
    mkdir "$HOME/windowsMounts/jwinalienC"
    sudo mount //192.168.1.102/C $HOME/windowsMounts/jwinalienC -o user=jwinalien -o uid=1000 -o gid=1000
fi    
