#!/bin/bash

#I have various drives on a windows PC that I like to mount as the local user
#All machines have a static IP

sudo mount //192.168.1.101/C /home/jfedalien/windowsMounts/mediapcC -o user=mediauser -o uid=1000 -o gid=1000
